platform :ios, '9.0'
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

target 'NotificationOCUnitTestTests' do
        pod 'Specta', '1.0.6'
        pod 'Expecta', '1.0.6'
        pod 'OCMock', '3.4'
end


